### ISSUE TITLE
Unable to access LC_API

### ISSUE THREAD

**Issue by dexbytesmanish** [livechat/angular-livechat#11]
I want to access LC_API events to perform some actions on callback functions but I don't have access to LC_API.

**Comment by lukiq** [comment]
Could you show me how do you try to access LC_API?

Have you checked our documentation: https://developers.livechatinc.com/docs/js-api/#on-before-load?

**Comment by dexbytesmanish** [comment]
This is working for me now.

**Comment by rmcsharry** [comment]
@dexbytesmanish How did you get it to work?

I keep getting error:

LC_API.set_visitor_email is not a function at SafeSubscriber._next

**Comment by MichalPaszowski** [comment]
Hi,

We apologise that you had to wait so long for a response.
We have prepared a new version of our library. This repository has been updated and the library can be found on NPM https://www.npmjs.com/package/@livechat/angular-widget.

Please give it a try and if necessary open new issue.
