### ISSUE TITLE
The Plunker's Broken.

### ISSUE THREAD

**Issue by dhmorrison** [livechat/angular-livechat#13]
Yup.  **Broken.**

The sample does not get past [...loading](http://plnkr.co/edit/bvMZNePnRJPIFPeKd1Ep?p=preview)

Seems like a cool idea, as the peoplesoft chat thing does not seem to play well with angular spa apps.  Out of curiosity, are you still actively developing this?

**Comment by rmcsharry** [comment]
I would like to know also...is this an active project?

**Comment by MichalPaszowski** [comment]
Hi,

We apologise that you had to wait so long for a response.
We have prepared a new version of our library. This repository has been updated and the library can be found on NPM https://www.npmjs.com/package/@livechat/angular-widget.

Please give it a try and if necessary open new issue.
