### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by erezharpaz** [livechat/angular-livechat#14]
The widget works fine in edge, but when opening the page in IE 11, I get an error:
"SCRIPT1010: Expected identifier"

any idea of what may be the problem?

**Comment by MichalPaszowski** [comment]
Hi,

We apologise that you had to wait so long for a response.
We have prepared a new version of our library. This repository has been updated and the library can be found on NPM https://www.npmjs.com/package/@livechat/angular-widget.

Please give it a try and if necessary open new issue.
