### ISSUE TITLE
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

### ISSUE THREAD

**Issue by romelgomez** [livechat/angular-livechat#19]
Browser Warning 

ref: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

![Screenshot from 2019-06-07 17-22-24](https://user-images.githubusercontent.com/2358251/59136456-e9857900-8948-11e9-91c7-1e9fb430e377.png)

**Comment by MichalPaszowski** [comment]
Hi,

We apologise that you had to wait so long for a response.
We have prepared a new version of our library. This repository has been updated and the library can be found on NPM https://www.npmjs.com/package/@livechat/angular-widget.

Please give it a try and if necessary open new issue.
