### ISSUE TITLE
show/hide and pass parameter to angular live chat widget

### ISSUE THREAD

**Issue by rahulnighotxpo** [livechat/angular-livechat#21]
show/hide and pass parameter to angular live chat widget

**Comment by MichalPaszowski** [comment]
Hi,

We apologise that you had to wait so long for a response.
We have prepared a new version of our library. This repository has been updated and the library can be found on NPM https://www.npmjs.com/package/@livechat/angular-widget.

Please give it a try and if necessary open new issue.
