### ISSUE TITLE
changing the language 

### ISSUE THREAD

**Issue by MaroueneAbbes** [livechat/angular-livechat#26]
I created a specific group for the french version and specific routing but i need to reload the hole application to see the french version or return to the English version
Is there any solution for that?

**Comment by jaynardev** [comment]
Can someone please have a look and suggest the solution as i am facing same problem in my application?

**Comment by walaszczykm** [comment]
Hello 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The new Angular package: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular).

In the new implementation, you would just need to change the targeted group property (which is configured to use a different language) and Chat Widget will automatically reload its configuration to handle such change without the need to reload the website 🙂
