### ISSUE TITLE
Wrong files are installed with npm install --save @livechat/angular-widget

### ISSUE THREAD

**Issue by zeldystern** [livechat/angular-livechat#28]
Hello,

I am installing with npm install --save @livechat/angular-widget
but it seems to installing the wrong files as they don't match what I see here in github.
I have files like 'livechat-widget.component.d.ts' instead of 'livechat-widget.component.ts' in angular-widget/src.

**Comment by walaszczykm** [comment]
Hello 👋 
By using `npm install --save @livechat/angular-widget` you are installing the package from the NPM registry which contains bundled code ready to be used in your app, not a source code that can be found here on GitHub.
