### ISSUE TITLE
Removing scripts and chat container in DOM

### ISSUE THREAD

**Issue by jeffyzxc** [livechat/angular-livechat#29]
Hello, 

Is there a way to remove scripts and chat container in DOM? and add them again?

**Comment by walaszczykm** [comment]
Hello 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The new Angular package: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular).

In the new implementation, all you need to do to achieve this is to not render the component (unmount it) using for example conditions rendering 🙂
