### ISSUE TITLE
Can't hide the chat with ngIf

### ISSUE THREAD

**Issue by ivansci** [livechat/angular-livechat#31]
I can't hide the chat after logout.

"@angular/core": "~9.1.3",
"@livechat/angular-widget": "^0.2.2"

Use case: Only show chat when user is logged in
<livechat-widget #liveChatWidget *ngIf="user" [visitor]="visitor" licenseId=""></livechat-widget>

On landing on page the *ngIf hides the chat but after the user had been loggedin and out again the chat will not be hidden. After refresh it works again!

https://github.com/livechat/angular-livechat/issues/23
https://github.com/livechat/angular-livechat/issues/21
https://github.com/livechat/angular-livechat/issues/8

**Comment by walaszczykm** [comment]
Hello 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The new Angular package: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular).

We didn't observe such an issue on the new implementation but you can try it out and let us know what you think 🙂
