### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by RaDaPo** [livechat/angular-livechat#33]
I'm trying to build my Angular app, but i receive this error:

> **ERROR in ./node_modules/@livechat/angular-widget/fesm2015/livechat-angular-widget.js
> Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
> TypeError: Cannot read property 'kind' of undefined**

Do I need to update something? With **ng serve** it's working pretty good.

Angular CLI: 8.1.0
Node: 12.16.2
Npm: 6.14.4
@livechat/angular-widget: 0.3.1

**Comment by RaDaPo** [comment]
I found out how to fix this error. If someone else will face this issue, please change your **devDependencies**, and try to change your **angular-devkit** dependencies to the latest version

**Comment by ohabash** [comment]
I have this problem but i cant understand exactly what to do to solve it.
