### ISSUE TITLE
Chat not starts with logged in users name and email

### ISSUE THREAD

**Issue by mikewilson55** [livechat/angular-livechat#4]
If user login to site and starts chat then it asked to insert username and email id. So in angular 6, is there any way that username and email directly select and start chat directly. Currently i have used <livechat-widget licenseId="YOUR LICENSE ID" />.

**Comment by rmcsharry** [comment]
It would be a nice enhancement to be able to have these an inputs to the directive especially since SPA's almost always have a logged in user that we know about. So adding them to the directive would make me use the directive....otherwise not much use really.

**Comment by MichalPaszowski** [comment]
Hi,

We apologise that you had to wait so long for a response.
We have prepared a new version of our library. This repository has been updated and the library can be found on NPM https://www.npmjs.com/package/@livechat/angular-widget.

Please give it a try and if necessary open new issue.
