### ISSUE TITLE
Not able to install the package for "@angular/core": "11.0.2"

### ISSUE THREAD

**Issue by tonisiforou** [livechat/angular-livechat#40]
Hello, 

I tried to install the package and I couldn't been able to do that because the package requires a peer of @angular/core@>=2.4.0 <10.0.0

Are you aware for that issue? 
Do you have any plans to make it support latest versions of angular/core in the near future?
Could you please check and advice?

**Comment by optimistex** [comment]
@tonisiforou Moreover, after look into the implementation I can see that the component uses the deprecated API v1.0 (legacy), and meanwhile there is v2.0 stable.

A question to the repository owners. Is there a way to have an update with usage of the actual API version?

**Comment by walaszczykm** [comment]
Hello @Juli125032 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The new Angular package: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular).

In the new implementation, we currently support Angular 11 and 12 🙂
