### ISSUE TITLE
 I'm trying integrate it in ionic/angular but the method onChatLoaded doesn't works

### ISSUE THREAD

**Issue by Juli125032** [livechat/angular-livechat#45]

**Comment by Juli125032** [comment]
It never runs

**Comment by walaszczykm** [comment]
Hello @Juli125032 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The new Angular package: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular).

It contains a newly implemented set of event listeners 🙂
