### ISSUE TITLE
LiveChat not displayed when Bizible script added to head

### ISSUE THREAD

**Issue by stepkillah** [livechat/angular-livechat#49]
Hi, we are using LiveChat angular component and it was working fine prior to we added Bizible to the `head` tag. When we using LiveChat js directly - it works fine, when we trying to use the angular component - it's never get initialized.

After a bit of investigation, we found a workaround by using this code before adding LiveChat widget 
`window['LC_API'] = null; // Fix for conflicting with bizible`

Any thoughts on why it's not working properly with bizible script?

**Comment by walaszczykm** [comment]
Hello @stepkillah 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The new Angular package: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular).
