### ISSUE TITLE
Livechat Group Refresh,

### ISSUE THREAD

**Issue by jaynardev** [livechat/angular-livechat#51]
Hi, 
I am trying to change group of livechat  on the basis of user selection. it works fine in development environment(JIT Compilation) and when it doesn't work with Production Build (AOT complication.). 

So, Can you please have a look and suggest. 

Code
======
  <livechat-widget  #livechatwidget group="{{selectedChatGroupCode}}" licenseId="{{liveChatLicense}}" >
    </livechat-widget>

Package.Json 
=======
  "@angular/common": "~11.0.2",
    "@angular/compiler": "~11.0.2",
    "@angular/core": "~11.0.2",
    "@angular/forms": "~11.0.2",
    "@angular/localize": "~11.0.2",
    "@angular/platform-browser": "~11.0.2",
    "@angular/platform-browser-dynamic": "~11.0.2",
    "@angular/router": "~11.0.2",
    "@livechat/angular-widget": "^0.3.1",

Thanks, 
Jay

**Comment by walaszczykm** [comment]
Hello @jaynardev 👋

I am happy to say that we have created a new set of packages to support more frontend frameworks integration with LiveChat Chat Widget: [Chat Widget Adapters](https://github.com/livechat/chat-widget-adapters) 🙂

From now on it will be the official, actively maintained repository for each framework-specific package that allows easy integration of LiveChat Chat Widget. The new Angular package: [@livechat/widget-angular](https://npm.im/@livechat/widget-angular).

In the new implementation, we treat all component properties as reactive, and the state of Chat Widget refreshes properly 😉
