### ISSUE TITLE
Property 'Support' does not exist on type 'DashboardComponent'.

### ISSUE THREAD

**Issue by adilmalik393** [livechat/angular-livechat#6]
I have added into my app.component.html this below line 

`<livechat-widget [licenseId]="licenseId" [group]="Support"></livechat-widget>`

And when I run `ng build --prod --aot`, It gives me following error.

**ERROR in src/app/dashboard/dashboard.component.html(4,42): : Property 'Support' does not exist on type 'DashboardComponent'.**

**Comment by adilmalik393** [comment]
I have solved the issue by changing my group assignment to this 

`<livechat-widget [licenseId]="licenseId" group="'Support'"></livechat-widget>`

Name of group should be string 'Support'

**Comment by lukiq** [comment]
It won't work, as the tracking don't have the option to pass the group name.
You can do it only using groupID: http://take.ms/azW3f.

There is always an option to do it via url rules.
You can read more about it here: https://www.livechatinc.com/kb/setting-up-url-rules-for-groups/.

**Comment by umerzaman** [comment]
I have an issue in angular 6  LC_API.hide_chat_window(); in compile time its giving error LC_API Cannot find name
