### ISSUE TITLE
Setting user name and email after LC is loaded

### ISSUE THREAD

**Issue by MarkoSulamagi** [livechat/angular-livechat#7]
How can I set user name and email to LiveChat after script has been loaded?

I have a Single Page app (angular). I'm not using angular-livechat library, because it seems a bit outdated. Instead I inject the LC JS script into the code manually. And this all works fine without any issues.

I understand there's LC_API available in here: https://developers.livechatinc.com/docs/js-api/#using-chat-window-api and in there is a method `LC_API.set_custom_variables(custom_variables);` that does the trick for custom variables. But how about email and name?

**Comment by ZiggyKraus** [comment]
Hello Marko!

Unfortunately, there's no way to push the **name** and **email** values after the code has already loaded, but if you are injecting our LiveChat's JS methods into your code manually, you can use the following method:

```
window.__lc.visitor = {
  name: 'Joe Public',
  email: 'joe.public@gmail.com'
}; 
```

With the use of it, whenever a customer will, for example, log into your app and LiveChat code with **lc.visitor** method will load as well, the **name** and **email** fields will automatically pre-fill the pre-chat survey, thus being available for your agents during a chat. You will just need to make sure that your system will pass over the required data :)

**Comment by MarkoSulamagi** [comment]
That's unfortunate. The problem is that LiveChat is already loaded when user signs in. 

Use case:
1. User is on login page
2. LiveChat is loaded without `visitor` data
3. User logs in (or registers) and is redirected to authenticated portion of page. LiveChat is still loaded. There's no page refresh
4. How can I set the name/email now?

**Comment by MarkoSulamagi** [comment]
@ZiggyKraus any thoughts on this? It's quite important issue for our support team

**Comment by ZiggyKraus** [comment]
Unfortunately, at the moment we do not have an easy way to work around this particular case. To prefill the **name** and **email** after your customers have already logged in, you would have to ensure that there's a page refresh that will reload LiveChat's code and attach your customers' data to `lc.visitor` method.

However, there might be a different way of implementing LiveChat that I can offer: you could, for example, provide your customers with the possibility to start a chat with the use of a direct link to which you can attach the **name** and **email** parameters as well. Here's how that link would look like:

`https://secure.livechatinc.com/licence/XXXXXX/open_chat.cgi?name=JohnDoe&email=john@doe.com`

You can use this link and attach it to your custom button that would open the chat – there are just two things that you have to remember about when using this kind of implementation. If you add it as a custom button, the chat will be opened in a new tab (or some webview implemented within your app), and you will have to remember to populate the parameters in the link after your customers will log into the app.

@MarkoSulamagi let me know if that is something that would work for you. Thank you very much in advance!

**Comment by MarkoSulamagi** [comment]
Thanks for the ideas @ZiggyKraus .That's very unfortunate. I'd add this to the feature requests list if you have one.

- Refreshing the page is one option, but doing this just for LiveChat is not something we'd like to do.
- The custom button kind of defeats the purpose of a simple chat integration. So that's not an option either.

Sadly it looks like we're going to have to look for other alternatives to LiveChat

**Comment by ZiggyKraus** [comment]
@MarkoSulamagi I'm very sorry to hear that :( I can ensure you that those feature requests are already on our developer's **todo** list and we will do our best to implement them as fast as possible, however I cannot give you a solid ETA at the moment.

Also, I have got one more suggestion in mind, regarding the `lc.visitor` parameter: you could implement a **lazy loading** module into your SPA application. For example, you could add some button at the bottom of your app that will load our chat script on demand, with `lc.visitor` attached to it – that will make sure that LiveChat's code will not be loaded whenever your customer will enter your app but only when he will start a chat with you, making sure that the lc.visitor parameter will still load.

Please let me know if you will have some additional questions about it and we will do our best to help!
