### ISSUE TITLE
When i navigate to other Component chat widget should hide

### ISSUE THREAD

**Issue by umerzaman** [livechat/angular-livechat#8]
In my angular app when i move to other component chat widget is not hiding in my case
<livechat-widget *ngIf="isLogin()" licenseId="My ID" group="My Group Id">  
</livechat-widget>

**Comment by Nastaliss** [comment]
The component should also hide if its ngIf condition is false.

**Comment by rahulnighotxpo** [comment]
have u got any solution?

**Comment by MichalPaszowski** [comment]
Hi,

We apologise that you had to wait so long for a response.
We have prepared a new version of our library. This repository has been updated and the library can be found on NPM https://www.npmjs.com/package/@livechat/angular-widget.

Please give it a try and if necessary open new issue.

**Comment by umerzaman** [comment]
> have u got any solution?

not yet... but  new version is come i will check it later
